- name: Install apache httpd  (state=present is optional)
  become: yes
  apt: name=apache2 state=latest

- name: index.html
  become: yes
  copy:
    content: "this is ansible playbook"
    dest: /var/www/html/index.html
  
- name: restart apache2
  become: yes
  service:
     name: apache2
     state: restarted