---
# Update and upgrade apt packages
  - name: Update and upgrade apt packages
    become: yes
    apt:
      upgrade: dist
      update_cache: yes
      cache_valid_time: 86400 #One day

# Install JDK 11
  - name: install JDK 11
    become: yes
    apt:
      name: openjdk-11-jdk
      state: present

  - name: Unarchive a file that needs to be downloaded (added in 2.0)
    become: yes
    unarchive:
      src: http://mirrors.estointernet.in/apache/tomcat/tomcat-9/v9.0.40/bin/apache-tomcat-9.0.40.tar.gz
      dest: /usr/local
      remote_src: yes
   
  - name: start tomcat
    become: yes
    shell: nohup /usr/local/apache-tomcat-9.0.40/bin/startup.sh &
